### ISSUE TITLE
Demo website is broken

### ISSUE THREAD

**Issue by GideonStowell** [accept-nano/accept-nano#12]
The [demo](https://rawgit.com/accept-nano/accept-nano-client/master/example/index.html) website seems to be broken. 

The API host is set as accept-nano-demo.put.io
Amount is 0.000001
Currency is NANO
State is left blank (bc there are no instructions on what it does or means)

I then click start and get a popup that says:

```
Oops!
An error occured: NETWORK_ERROR
```
This isn't really enough to know if it is my problem or not. I have tried both on mobile and desktop and got the same result.

In the dev console I can see this single error:
`Failed to load resource: the server responded with a status of 500 ()   accpet-nano-demo.put.io/api/pay`

**Comment by BatuAksoy** [comment]
Hey @GideonStowell,
I think that is related to recent change of NANO code. It is XNO now. When you choose USD, it should work as expected. But that is related to https://github.com/accept-nano/accept-nano-client

With this commit it should be fixed: https://github.com/accept-nano/accept-nano-client/commit/dc1824e63a0c30c4e028a1fbc3dcc619a9b19825

**Comment by BatuAksoy** [comment]
ping @cenkalti, I can't close the issue

**Comment by cenkalti** [comment]
Thanks @BatuAksoy
