### ISSUE TITLE
Sender address in API

### ISSUE THREAD

**Issue by BitDesert** [accept-nano/accept-nano#2]
Hey guys,

I would like to integrate this into mynano.ninja, but I need the information which account sent the payment.
Currently I'm using brainblocks which has a "sender" field in the verify API call. I know that accept-nano allows multiple sub-payments, but would it be possible to integrate an array to the response with the sending accounts?

Let me know what you think. Thanks!

**Comment by cenkalti** [comment]
Hello @BitDesert I have added `subPayments` field to the `/api/verify` response.
Example:
```sh
$ http get localhost:5000/api/verify token==eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbmRleCI6IjQ4NjQxNzQ3MjgwNTQ5OTk2MzAiLCJhY2NvdW50IjoieHJiXzF3Z3RpbnNvZDZqaHA0N2M0bXB4cHJpdWllM3JjeWt1ODVmaTcxZWQ2emRoZ3B0eTMxZmI4d25ucXNkZyJ9.XTv8zeOBcvn7KlC6TSzR4p_qCq8Jbn7vmWUFVBXl8HQ
HTTP/1.1 200 OK
Content-Length: 649
Content-Type: text/plain; charset=utf-8
Date: Mon, 22 Oct 2018 08:22:43 GMT
Vary: Origin

{
    "account": "xrb_1zxcvnsod6jhp47c4mpxpriuie3rcyku85fi71ed6zdhgpty31fb8wnnqsdg",
    "amount": "0.001",
    "amountInCurrency": "0.001",
    "balance": "0.001",
    "currency": "NANO",
    "fulfilled": true,
    "merchantNotified": true,
    "remainingSeconds": 45,
    "state": "",
    "subPayments": {
        "707D846645839C6D24885FB3349E37198A9622AD03B9469AB9CD09583A2FEC35": {
            "account": "xrb_1asdf13d5i7qi51ox3m8ipdqecuagopihyb5snffd49b8zo6pq68gqc89nfw",
            "amount": "0.001"
        }
    },
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbmRleCI6IjQ4NjQxNzQ3MjgwNTQ5OTk2MzAiLCJhY2NvdW50IjoieHJiXzF3Z3RpbnNvZDZqaHA0N2M0bXB4cHJpdWllM3JjeWt1ODVmaTcxZWQ2emRoZ3B0eTMxZmI4d25ucXNkZyJ9.XTv8zeOBcvn7KlC6TSzR4p_qCq8Jbn7vmWUFVBXl8HQ"
}
```

Does that solve your issue?

**Comment by cenkalti** [comment]
I can't release a new version though. Travis build does not get triggered because GitHub is experiencing some service outage right now. https://status.github.com/

**Comment by BitDesert** [comment]
If `xrb_1asdf13d5i7qi51ox3m8ipdqecuagopihyb5snffd49b8zo6pq68gqc89nfw` is the senders account that's perfect! Thanks!

**Comment by cenkalti** [comment]
GitHub and Travis are back. New version is released: https://github.com/accept-nano/accept-nano/releases/tag/v1.2.0

**Comment by cenkalti** [comment]
Hi @BitDesert, this is a notification. I have made some updates to accept-nano. Maybe you want to upgrade. The new version has the Websocket support so the confirmations are faster and verifying a payment does not have to wait for next poll interval. Just add the node's websocket URL in the config. Please let me know if you have questions.

**Comment by BitDesert** [comment]
Just created a PR for a docker image #6 , wanted to update my stack anyway. So a docker image would be awesome.
Anything planned for using websockets on the client side too? @cenkalti

**Comment by cenkalti** [comment]
@BitDesert thank you. I have one question on the PR: https://github.com/accept-nano/accept-nano/pull/6#discussion_r432828605

I have also created an issue for websockets on the client side but I am not good at Javascript: https://github.com/accept-nano/accept-nano-client/issues/5
