### ISSUE TITLE
Secure API key in Travis config

### ISSUE THREAD

**Issue by BitDesert** [accept-nano/accept-nano#3]
https://github.com/accept-nano/accept-nano/blob/b616f63a748d887de61999e2e33de59b723ea370/.travis.yml#L21

**Comment by cenkalti** [comment]
It's already encrypted via travis CLI. https://docs.travis-ci.com/user/encryption-keys/#usage

What's you concern here?

**Comment by BitDesert** [comment]
Thought this was a leaked secure key. Sorry!
