### ISSUE TITLE
[Centralized Bug] CoinmarketcapAPIKey error when using non-fiat currency

### ISSUE THREAD

**Issue by gigaion** [accept-nano/accept-nano#9]
Assuming accept-nano-client scenario:
`session.createPayment({amount: '1', currency: 'NANO', state: 'Example'})`
		
accept-nano will error with the following message (using no API key):
`http.go:93 empty CoinmarketcapAPIKey value in config`

accept-nano will error with the following message (using invalid API key):
`http.go:93 bad ticker response`

accept-nano should ignore doing an API call when currency is specified as NANO. Paying for coinmarketcap API fees when not needed for fiat conversions should be fixed.

**Comment by BatuAksoy** [comment]
Hey @Gigaion,
I think if you leave currency field empty, you can prevent API call to coinmarketcap.

I checked out the error you mentioned and saw that:
https://github.com/accept-nano/accept-nano/blob/6f0448b1985455b640382feb82b2412621f9ec31/http.go#L89-L101

**Comment by gigaion** [comment]
@BatuAksoy 
Thank you for the reply. It seems your solution has worked on leaving it blank.

However I recommend this snippet alteration as to prevent API calls when not required.
(Incase future people do the same mistake I've presented):

`if currency != "" && currency != "NANO" { ... }`

**Comment by BatuAksoy** [comment]
I think it would be very great to implement your suggestion. I will do necessary adjustments. Thank you for the heads up!!
